const $=(id)=>document.getElementById(id);
const send=(type,extra={})=>new Promise((resolve,reject)=>chrome.runtime.sendMessage({type,...extra},(r)=>{if(chrome.runtime.lastError)return reject(chrome.runtime.lastError);if(!r?.ok)return reject(new Error(r?.error||"Không thực hiện được."));resolve(r.result)}));
const rel=(ms)=>{if(!ms)return"Chưa đồng bộ";const d=Math.max(0,Date.now()-Number(ms));if(d<60000)return"Vừa đồng bộ";if(d<3600000)return`${Math.floor(d/60000)} phút trước`;return`${Math.floor(d/3600000)} giờ trước`};
const msg=(t,c="")=>{$("result").textContent=t||"";$("result").className=`message ${c}`};
async function ensureServerPermission(value){const url=new URL(String(value||"").trim()),known=url.hostname.endsWith(".vercel.app")||["tranductai.xyz","www.tranductai.xyz"].includes(url.hostname)||["localhost","127.0.0.1"].includes(url.hostname);if(known)return true;const originPattern=`${url.origin}/*`;if(await chrome.permissions.contains({origins:[originPattern]}))return true;const granted=await chrome.permissions.request({origins:[originPattern]});if(!granted)throw new Error("Chrome chưa cấp quyền truy cập custom domain T Balance.");return true}
async function load(){const s=await send("GET_STATE");const l=s.local||{},server=s.server||{},auth=!!s.device?.authorized;$("serverBase").value=l.serverBase||"";$("pairBox").style.display=auth?"none":"grid";$("dot").className=`dot ${auth?(server.healthy?"ok":"warn"):"bad"}`;$("status").textContent=auth?`Đã ghép · ${server.accountCount||0} TKQC`:"Chưa ghép với T Balance";$("lastSync").textContent=rel(server.lastSyncAtMs||l.lastSyncAt);$("autoSync").checked=l.autoSync!==false;$("autoBatchScan").checked=l.autoBatchScan===true;$("interval").value=String(l.intervalMinutes||30);$("batchSize").value=String(l.batchSize||10);$("closeTabs").checked=l.closeBatchTabs!==false;$("deviceName").value=l.deviceName||"Meta Billing Extension";if(l.lastError)msg(l.lastError,"bad")}
async function busy(btn,fn){const b=$(btn);b.disabled=true;try{return await fn()}finally{b.disabled=false}}
$("pairCode").addEventListener("input",e=>e.target.value=e.target.value.replace(/\D/g,"").slice(0,8));
$("pairBtn").onclick=()=>busy("pairBtn",async()=>{msg("Đang ghép…");await ensureServerPermission($("serverBase").value);await send("PAIR",{pairingCode:$("pairCode").value,serverBase:$("serverBase").value});msg("Ghép thành công.","ok");await load()}).catch(e=>msg(e.message,"bad"));
$("scanOpen").onclick=()=>busy("scanOpen",async()=>{msg("Đang đọc các tab Billing đang mở…");const r=await send("SCAN_OPEN");msg(`Đã cập nhật ${r.updated||r.scanned||0} TKQC.`,"ok");await load()}).catch(e=>msg(e.message,"bad"));
$("scanAll").onclick=()=>busy("scanAll",async()=>{msg("Đang quét lần lượt Billing Hub. Không đóng trình duyệt…");const r=await send("SCAN_ALL");msg(`Thành công ${r.succeeded||r.updated||0}/${r.attempted||r.scanned||0} TKQC.`,r.succeeded?"ok":"bad");await load()}).catch(e=>msg(e.message,"bad"));
$("openBilling").onclick=()=>send("OPEN_BILLING");$("openWeb").onclick=()=>send("OPEN_TBALANCE");
$("save").onclick=()=>busy("save",async()=>{await ensureServerPermission($("serverBase").value);await send("SAVE",{settings:{serverBase:$("serverBase").value,deviceName:$("deviceName").value,autoSync:$("autoSync").checked,autoBatchScan:$("autoBatchScan").checked,intervalMinutes:Number($("interval").value),batchSize:Number($("batchSize").value),closeBatchTabs:$("closeTabs").checked}});msg("Đã lưu cài đặt.","ok");await load()}).catch(e=>msg(e.message,"bad"));
load().catch(e=>msg(e.message,"bad"));
